#!/usr/bin/env python3
"""Generate EXTRA dev seed SQL — 4 more historical periods (P5..P8).

Companion to gen-dev-seed.py. Leaves the original 028-031 files untouched;
emits new numbered files (040-043) appended via new changesets.

Layout (today = 2026-05-20):
    P5  QUARTERLY  2025-01-01..2025-03-31  CLOSED
    P6  QUARTERLY  2025-04-01..2025-06-30  CLOSED
    P7  QUARTERLY  2025-07-01..2025-09-30  CLOSED
    P8  MONTHLY    2025-08-01..2025-08-31  CLOSED

All 4 periods CLOSED — every evaluation CLOSED with a final_score.

Antibonus: criteria 9 & 10 weight raised 5%->15% (changeset 039). These
periods seed history rows with weight_snapshot=15 and large raw values, so
the antibonus deduction is 10-20 pts and visibly drops offender ratings.
"""
from pathlib import Path

OUT_DIR = Path(__file__).resolve().parents[1] / "src/main/resources/db/changelog/m6"

# (user_id, manager_id) — same 27 employees as gen-dev-seed.py
USERS = [
    (3, 2), (4, 2), (5, 3), (6, 3), (7, 4), (8, 4), (9, 4), (10, 7), (11, 7),
    (12, 5), (13, 5), (14, 5), (15, 5),
    (16, 6), (17, 6), (18, 6),
    (19, 10), (20, 10), (21, 10), (22, 10),
    (23, 11), (24, 11),
    (25, 8), (26, 8), (27, 8),
    (28, 9), (29, 9),
]
assert len(USERS) == 27

PERSONALITY = {12: "high", 19: "high", 25: "high",
               16: "low",  23: "low",  28: "low"}
TARGET = {"high": 92, "avg": 77, "low": 60}

# (criteria_id, type, weight) — antibonus weights bumped to 15 (see changeset 039)
CRITERIA = [
    (1,  "POSITIVE",   20.0),
    (2,  "POSITIVE",   15.0),
    (3,  "POSITIVE",   15.0),
    (4,  "POSITIVE",   10.0),
    (5,  "POSITIVE",   10.0),
    (6,  "POSITIVE",   10.0),
    (7,  "POSITIVE",   10.0),
    (8,  "POSITIVE",   10.0),
    (9,  "ANTI_BONUS", 15.0),
    (10, "ANTI_BONUS", 15.0),
]

# (id, type, start, end, deadline, created_at, closed_at) — all CLOSED
PERIODS = [
    (5, 'QUARTERLY', '2025-01-01', '2025-03-31', '2025-04-05 18:00:00',
     '2024-12-15 10:00:00', '2025-04-10 10:00:00'),
    (6, 'QUARTERLY', '2025-04-01', '2025-06-30', '2025-07-05 18:00:00',
     '2025-03-15 10:00:00', '2025-07-10 10:00:00'),
    (7, 'QUARTERLY', '2025-07-01', '2025-09-30', '2025-10-05 18:00:00',
     '2025-06-15 10:00:00', '2025-10-10 10:00:00'),
    (8, 'MONTHLY',   '2025-08-01', '2025-08-31', '2025-09-05 18:00:00',
     '2025-07-20 10:00:00', '2025-09-10 10:00:00'),
]

# (created, submitted, updated) per period id
PERIOD_DATES = {
    5: ('2025-01-06 09:00:00', '2025-04-03 14:00:00', '2025-04-10 10:00:00'),
    6: ('2025-04-07 09:00:00', '2025-07-03 14:00:00', '2025-07-10 10:00:00'),
    7: ('2025-07-07 09:00:00', '2025-10-03 14:00:00', '2025-10-10 10:00:00'),
    8: ('2025-08-04 09:00:00', '2025-09-03 14:00:00', '2025-09-10 10:00:00'),
}

START_EVAL_ID = 109  # gen-dev-seed.py ends at 108


def raw_positive(uid, cid, target, salt):
    offset = ((uid * 7 + cid * 13 + salt * 17) % 11) - 5
    return float(max(50, min(100, target + offset)))


def raw_antibonus(uid, cid, salt):
    """Large antibonus raw values. Offenders 40-62, others 12-28 — always >10."""
    if uid in PERSONALITY and PERSONALITY[uid] == "low":
        base = 40 + ((uid * 3 + cid * 5 + salt * 11) % 23)   # 40..62
    else:
        base = 12 + ((uid * 3 + cid * 5 + salt * 11) % 17)   # 12..28
    return float(base)


def raw_value(uid, cid, ctype, target, salt):
    return raw_positive(uid, cid, target, salt) if ctype == "POSITIVE" \
        else raw_antibonus(uid, cid, salt)


def final_score(uid, salt):
    target = TARGET[PERSONALITY.get(uid, "avg")]
    pos = sum(raw_value(uid, c, t, target, salt) * w / 100
              for (c, t, w) in CRITERIA if t == "POSITIVE")
    anti = sum(raw_value(uid, c, t, target, salt) * w / 100
               for (c, t, w) in CRITERIA if t == "ANTI_BONUS")
    return round(max(0.0, pos - anti), 2)


def sql_lit(v):
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, str):
        return "'" + v.replace("'", "''") + "'"
    return str(v)


def write_rows(fname, table, cols, rows):
    body = ",\n  ".join("(" + ", ".join(sql_lit(c) for c in r) + ")" for r in rows)
    (OUT_DIR / fname).write_text(
        "-- generated by backend/scripts/gen-dev-seed-extra.py — do not hand-edit\n"
        f"INSERT INTO {table} {cols} VALUES\n  {body};\n"
    )


def main():
    period_rows, eval_rows, score_rows, hist_rows = [], [], [], []

    for (pid, typ, sd, ed, dl, ca, closed) in PERIODS:
        period_rows.append((pid, typ, sd, ed, dl, 'CLOSED', False, 1, ca, closed))

    eval_id = START_EVAL_ID
    for (pid, typ, sd, ed, dl, ca, closed) in PERIODS:
        created, submitted, updated = PERIOD_DATES[pid]
        salt = pid  # distinct per period
        for (uid, mid) in USERS:
            target = TARGET[PERSONALITY.get(uid, "avg")]
            fs = final_score(uid, salt)
            eval_rows.append((eval_id, pid, uid, mid, 'CLOSED', fs, 0,
                              'Период закрыт; оценка зафиксирована.',
                              submitted, created, updated))
            for (cid, ctype, w) in CRITERIA:
                raw = round(raw_value(uid, cid, ctype, target, salt), 4)
                score_rows.append((eval_id, cid, raw, None, submitted))
                hist_rows.append((eval_id, cid, raw, round(raw * w / 100, 4),
                                  w, updated, ctype))
            eval_id += 1

    write_rows("040-seed-periods-extra.sql", "evaluation_periods",
               "(id, type, start_date, end_date, submission_deadline, status, "
               "auto_created, created_by, created_at, closed_at)", period_rows)
    write_rows("041-seed-evaluations-extra.sql", "evaluations",
               "(id, period_id, evaluatee_id, evaluator_id, status, final_score, "
               "version, evaluatee_comment, submitted_at, created_at, updated_at)",
               eval_rows)
    write_rows("042-seed-evaluation-scores-extra.sql", "evaluation_scores",
               "(evaluation_id, criteria_id, value, note, updated_at)", score_rows)
    write_rows("043-seed-score-history-extra.sql", "evaluation_score_history",
               "(evaluation_id, criteria_id, raw_value, weighted_value, "
               "weight_snapshot, recorded_at, criteria_type)", hist_rows)

    print(f"Wrote 4 files: {len(period_rows)} periods, {len(eval_rows)} evaluations, "
          f"{len(score_rows)} scores, {len(hist_rows)} history rows.")
    print(f"Eval ids {START_EVAL_ID}..{eval_id - 1}")


if __name__ == "__main__":
    main()
