#!/usr/bin/env python3
"""Generate dev seed SQL for evaluations / scores / history.

Usage:
    python3 backend/scripts/gen-dev-seed.py

Writes:
    backend/src/main/resources/db/changelog/m6/029-seed-evaluations.sql
    backend/src/main/resources/db/changelog/m6/030-seed-evaluation-scores.sql
    backend/src/main/resources/db/changelog/m6/031-seed-score-history.sql
"""
from pathlib import Path

OUT_DIR = Path(__file__).resolve().parents[1] / "src/main/resources/db/changelog/m6"
OUT_DIR.mkdir(parents=True, exist_ok=True)

# (user_id, manager_id) — copy of the table from Task 4, chairman excluded
USERS = [
    (3, 2), (4, 2), (5, 3), (6, 3), (7, 4), (8, 4), (9, 4), (10, 7), (11, 7),
    (12, 5), (13, 5), (14, 5), (15, 5),
    (16, 6), (17, 6), (18, 6),
    (19, 10), (20, 10), (21, 10), (22, 10),
    (23, 11), (24, 11),
    (25, 8), (26, 8), (27, 8),
    (28, 9), (29, 9),
]
assert len(USERS) == 27

PERSONALITY = {12: "high", 19: "high", 25: "high",
               16: "low",  23: "low",  28: "low"}
TARGET = {"high": 92, "avg": 77, "low": 60}

# (criteria_id, type, weight)
CRITERIA = [
    (1,  "POSITIVE",   20.0),
    (2,  "POSITIVE",   15.0),
    (3,  "POSITIVE",   15.0),
    (4,  "POSITIVE",   10.0),
    (5,  "POSITIVE",   10.0),
    (6,  "POSITIVE",   10.0),
    (7,  "POSITIVE",   10.0),
    (8,  "POSITIVE",   10.0),
    (9,  "ANTI_BONUS",  5.0),
    (10, "ANTI_BONUS",  5.0),
]

# Q1 appeal outcomes by user_id
Q1_APPEAL_DELTA = {16: 5.0, 23: 3.0, 28: 0.0}  # 28 = OVERTURNED → no change

def raw_value(user_id: int, criteria_id: int, ctype: str, target: int) -> float:
    if ctype == "POSITIVE":
        offset = ((user_id * 7 + criteria_id * 13) % 11) - 5
        return float(max(50, min(100, target + offset)))
    else:
        v = ((user_id * 3 + criteria_id * 5) % 7) - 3
        return float(max(0, v))

def final_score(user_id: int) -> float:
    target = TARGET[PERSONALITY.get(user_id, "avg")]
    pos = sum(raw_value(user_id, cid, t, target) * w / 100
              for (cid, t, w) in CRITERIA if t == "POSITIVE")
    anti = sum(raw_value(user_id, cid, t, target) * w / 100
               for (cid, t, w) in CRITERIA if t == "ANTI_BONUS")
    return round(max(0.0, pos - anti), 2)

def q1_eval_rows():
    rows = []
    for idx, (uid, mid) in enumerate(USERS):
        eval_id = idx + 1
        score = final_score(uid) + Q1_APPEAL_DELTA.get(uid, 0.0)
        # columns: id, period_id, evaluatee_id, evaluator_id, status, final_score,
        #          version, evaluatee_comment, submitted_at, created_at, updated_at
        rows.append((eval_id, 1, uid, mid, "CLOSED",
                     round(score, 2),
                     0,
                     "Период закрыт; оценка зафиксирована.",
                     "2026-04-03 14:00:00",
                     "2026-01-15 09:00:00", "2026-04-10 10:00:00"))
    return rows

def q2_eval_rows():
    rows = []
    for idx, (uid, mid) in enumerate(USERS):
        eval_id = idx + 28
        if idx <= 10:
            status, submitted, fs = "SUBMITTED", "2026-05-08 11:00:00", final_score(uid)
            comment = "Оценка отправлена руководителем."
        elif idx <= 18:
            status, submitted, fs = "DRAFT", None, None
            comment = None
        elif idx <= 23:
            status, submitted, fs = "DRAFT", None, None
            comment = None
        else:
            status, submitted, fs = "APPEALED", "2026-05-06 11:00:00", final_score(uid)
            comment = "Оценка отправлена; подана апелляция."
        # columns: id, period_id, evaluatee_id, evaluator_id, status, final_score,
        #          version, evaluatee_comment, submitted_at, created_at, updated_at
        rows.append((eval_id, 2, uid, mid, status, fs, 0, comment, submitted,
                     "2026-04-02 09:00:00", "2026-05-08 11:00:00"))
    return rows

def sql_lit(v):
    if v is None: return "NULL"
    if isinstance(v, str): return "'" + v.replace("'", "''") + "'"
    return str(v)

def write_evaluations():
    rows = q1_eval_rows() + q2_eval_rows()
    cols = "(id, period_id, evaluatee_id, evaluator_id, status, final_score, version, evaluatee_comment, submitted_at, created_at, updated_at)"
    body = ",\n  ".join("(" + ", ".join(sql_lit(c) for c in r) + ")" for r in rows)
    (OUT_DIR / "029-seed-evaluations.sql").write_text(
        f"-- generated by backend/scripts/gen-dev-seed.py — do not hand-edit\n"
        f"INSERT INTO evaluations {cols} VALUES\n  {body};\n"
    )

def write_scores():
    out = ["-- generated by backend/scripts/gen-dev-seed.py — do not hand-edit"]
    cols = "(evaluation_id, criteria_id, value, note, updated_at)"
    score_rows = []

    for idx, (uid, _mid) in enumerate(USERS):
        eval_id = idx + 1
        target = TARGET[PERSONALITY.get(uid, "avg")]
        for (cid, ctype, _w) in CRITERIA:
            v = raw_value(uid, cid, ctype, target)
            score_rows.append((eval_id, cid, round(v, 4), None, "2026-04-03 14:00:00"))

    for idx, (uid, _mid) in enumerate(USERS):
        eval_id = idx + 28
        target = TARGET[PERSONALITY.get(uid, "avg")]
        if idx <= 10 or idx >= 24:
            for (cid, ctype, _w) in CRITERIA:
                v = raw_value(uid, cid, ctype, target)
                score_rows.append((eval_id, cid, round(v, 4), None, "2026-05-08 11:00:00"))
        elif idx <= 18:
            for (cid, ctype, _w) in CRITERIA[:4]:
                v = raw_value(uid, cid, ctype, target)
                score_rows.append((eval_id, cid, round(v, 4), None, "2026-05-05 11:00:00"))

    body = ",\n  ".join("(" + ", ".join(sql_lit(c) for c in r) + ")" for r in score_rows)
    out.append(f"INSERT INTO evaluation_scores {cols} VALUES\n  {body};")
    (OUT_DIR / "030-seed-evaluation-scores.sql").write_text("\n".join(out) + "\n")

def write_history():
    cols = "(evaluation_id, criteria_id, raw_value, weighted_value, weight_snapshot, recorded_at, criteria_type)"
    history_rows = []
    for idx, (uid, _mid) in enumerate(USERS):
        eval_id = idx + 1
        target = TARGET[PERSONALITY.get(uid, "avg")]
        for (cid, ctype, w) in CRITERIA:
            raw = raw_value(uid, cid, ctype, target)
            weighted = round(raw * w / 100, 4)
            history_rows.append((eval_id, cid, round(raw, 4), weighted, w,
                                 "2026-04-10 10:00:00", ctype))
    body = ",\n  ".join("(" + ", ".join(sql_lit(c) for c in r) + ")" for r in history_rows)
    (OUT_DIR / "031-seed-score-history.sql").write_text(
        "-- generated by backend/scripts/gen-dev-seed.py — do not hand-edit\n"
        f"INSERT INTO evaluation_score_history {cols} VALUES\n  {body};\n"
    )

if __name__ == "__main__":
    write_evaluations()
    write_scores()
    write_history()
    print("Wrote:")
    for f in ("029-seed-evaluations.sql", "030-seed-evaluation-scores.sql", "031-seed-score-history.sql"):
        print(" ", OUT_DIR / f)
