-- generated by backend/scripts/gen-dev-seed.py — do not hand-edit
INSERT INTO evaluation_periods (id, type, start_date, end_date, submission_deadline, status, auto_created, created_by, created_at, closed_at) VALUES
  (1, 'QUARTERLY', '2025-10-01', '2025-12-31', '2026-01-05 18:00:00', 'CLOSED', false, 1, '2025-09-15 10:00:00', '2026-01-10 10:00:00'),
  (2, 'QUARTERLY', '2026-01-01', '2026-03-31', '2026-04-05 18:00:00', 'CLOSED', false, 1, '2025-12-15 10:00:00', '2026-04-10 10:00:00'),
  (3, 'MONTHLY', '2026-05-01', '2026-05-31', '2026-06-05 18:00:00', 'ACTIVE', false, 1, '2026-04-20 10:00:00', NULL),
  (4, 'QUARTERLY', '2026-04-01', '2026-06-30', '2026-07-05 18:00:00', 'ACTIVE', false, 1, '2026-03-20 10:00:00', NULL);
