-- generated by backend/scripts/gen-dev-seed-extra.py — do not hand-edit
INSERT INTO evaluation_periods (id, type, start_date, end_date, submission_deadline, status, auto_created, created_by, created_at, closed_at) VALUES
  (5, 'QUARTERLY', '2025-01-01', '2025-03-31', '2025-04-05 18:00:00', 'CLOSED', false, 1, '2024-12-15 10:00:00', '2025-04-10 10:00:00'),
  (6, 'QUARTERLY', '2025-04-01', '2025-06-30', '2025-07-05 18:00:00', 'CLOSED', false, 1, '2025-03-15 10:00:00', '2025-07-10 10:00:00'),
  (7, 'QUARTERLY', '2025-07-01', '2025-09-30', '2025-10-05 18:00:00', 'CLOSED', false, 1, '2025-06-15 10:00:00', '2025-10-10 10:00:00'),
  (8, 'MONTHLY', '2025-08-01', '2025-08-31', '2025-09-05 18:00:00', 'CLOSED', false, 1, '2025-07-20 10:00:00', '2025-09-10 10:00:00');
